// <auto-generated />
using GestionObrasArte.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionObrasArte.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("GestionObrasArte.Shared.Models.Artista", b =>
                {
                    b.Property<int>("IdArtista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidosArtista")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AñoNacimientoArtista")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreArtista")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdArtista");

                    b.ToTable("Artistas");
                });

            modelBuilder.Entity("GestionObrasArte.Shared.Models.Pintura", b =>
                {
                    b.Property<int>("IdPintura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_IdTipoPintura")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fk_IdArtista")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("DECIMAL");

                    b.Property<string>("TituloPintura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdPintura");

                    b.HasIndex("FK_IdTipoPintura");

                    b.HasIndex("Fk_IdArtista");

                    b.ToTable("Pinturas");
                });

            modelBuilder.Entity("GestionObrasArte.Shared.Models.TipoPintura", b =>
                {
                    b.Property<int>("IdTipoPintura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TítuloTipoPintura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdTipoPintura");

                    b.ToTable("TiposPintura");
                });

            modelBuilder.Entity("GestionObrasArte.Shared.Models.Pintura", b =>
                {
                    b.HasOne("GestionObrasArte.Shared.Models.TipoPintura", "TipoPintura")
                        .WithMany()
                        .HasForeignKey("FK_IdTipoPintura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionObrasArte.Shared.Models.Artista", "Artista")
                        .WithMany()
                        .HasForeignKey("Fk_IdArtista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artista");

                    b.Navigation("TipoPintura");
                });
#pragma warning restore 612, 618
        }
    }
}
